# Generated by Django 2.2.16 on 2022-04-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220428_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(max_length=100, null=True, verbose_name='Код подтверждения'),
        ),
    ]
